language: node_js
node_js:
  - 14

services:
  - docker

before_install:
- docker run --rm --volume "`pwd`:/data" --entrypoint "/data/pandoc.sh" pandoc/latex:2.6

install:
- npm install

script:
- push.sh
