name: 'Build and push to S3'

# **What it does**: Renders the content of every page and check all internal links.
# **Why we have it**: To make sure all links connect correctly.
# **Who does it impact**: Docs content.

on: [push]

permissions:
  contents: read

jobs:
  convert:
    runs-on: pandoc/latex:2.6
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Convert docs
        run: ./pandoc.sh
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: Install
        run: npm ci

      - name: Push files to s3
        run: ./push.sh
